"""Added number of pages per question

Revision ID: 17a0d9d0f480
Revises: afb77e0eb63c
Create Date: 2025-11-04 15:48:15.005044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a0d9d0f480'
down_revision: Union[str, Sequence[str], None] = 'afb77e0eb63c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('pages', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student_workbook', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_workbook', type_='foreignkey')
    op.drop_column('question_bank', 'pages')
    # ### end Alembic commands ###
