"""fix to foreign key constraints

Revision ID: 3e4ae9fb2a77
Revises: fcca4c1c3fb6
Create Date: 2025-10-21 17:45:50.444793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4ae9fb2a77'
down_revision: Union[str, Sequence[str], None] = 'fcca4c1c3fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_workbook_ibfk_1'), 'student_workbook', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('student_workbook_ibfk_1'), 'student_workbook', 'question_bank', ['paper_id'], ['paper_id'])
    # ### end Alembic commands ###
