"""ip addr in logging

Revision ID: 59bea6c951a0
Revises: 489357d3f035
Create Date: 2025-10-14 11:55:47.826920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59bea6c951a0'
down_revision: Union[str, Sequence[str], None] = '489357d3f035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_log', sa.Column('ip_addr', sa.String(length=45), nullable=False))
    op.add_column('workbook_log', sa.Column('ip_addr', sa.String(length=45), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workbook_log', 'ip_addr')
    op.drop_column('user_log', 'ip_addr')
    # ### end Alembic commands ###
