"""added question to question_bank

Revision ID: c76db341f68a
Revises: 59bea6c951a0
Create Date: 2025-10-15 21:16:36.165056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76db341f68a'
down_revision: Union[str, Sequence[str], None] = '59bea6c951a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('question', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_bank', 'question')
    # ### end Alembic commands ###
